# Generated by Django 2.1.2 on 2019-07-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190717_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='domain',
        ),
    ]
