# Generated by Django 2.1.2 on 2019-07-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_post_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='domain',
            field=models.CharField(default='public', max_length=10),
            preserve_default=False,
        ),
    ]
